const arr = [
  { id: 1, address: require("../images/Exterior/ext1.jpeg") },
  { id: 2, address: require("../images/Exterior/ext2.jpeg") },
  { id: 3, address: require("../images/Exterior/ext3.jpeg") },
  { id: 4, address: require("../images/Exterior/ext4.jpeg") },
  { id: 5, address: require("../images/Exterior/ext5.jpeg") },
  { id: 10, address: require("../images/Interior/int1.jpeg") },
  { id: 11, address: require("../images/Interior/int2.jpeg") },
  { id: 12, address: require("../images/Interior/int3.jpeg") },
  { id: 13, address: require("../images/Interior/int4.jpeg") },
  { id: 6, address: require("../images/Exterior/ext6.jpeg") },
  { id: 7, address: require("../images/Exterior/ext7.jpeg") },
  { id: 8, address: require("../images/Exterior/ext8.jpeg") },
  { id: 9, address: require("../images/Exterior/ext9.jpeg") },
  { id: 14, address: require("../images/Interior/int5.jpeg") },
  { id: 15, address: require("../images/Interior/int6.jpeg") },
  { id: 16, address: require("../images/Interior/int7.jpeg") },
  { id: 17, address: require("../images/Interior/int8.jpeg") },
  { id: 18, address: require("../images/Interior/int9.jpeg") },
  { id: 19, address: require("../images/Interior/int10.jpeg") },
  { id: 20, address: require("../images/Mechanical/mech1.jpeg") },
  { id: 21, address: require("../images/Mechanical/mech2.jpeg") },
  { id: 22, address: require("../images/Mechanical/mech3.jpeg") },
  { id: 23, address: require("../images/Mechanical/mech4.jpeg") },
  { id: 24, address: require("../images/Mechanical/mech5.jpeg") },
  { id: 25, address: require("../images/Mechanical/mech6.jpeg") },
  { id: 26, address: require("../images/Mechanical/mech7.jpeg") },
  { id: 32, address: require("../images/Documents/doc1.jpeg") },
  { id: 27, address: require("../images/Documents/doc2.jpeg") },
  { id: 28, address: require("../images/Documents/doc3.jpeg") },
  { id: 29, address: require("../images/Documents/doc4.jpeg") },
  { id: 30, address: require("../images/Documents/doc5.jpeg") },
  { id: 31, address: require("../images/Documents/doc6.jpeg") },
  { id: 32, address: require("../images/Documents/doc7.jpeg") },
  { id: 33, address: require("../images/others/other1.jpeg") },
  { id: 34, address: require("../images/others/other2.jpeg") },
  { id: 35, address: require("../images/others/other3.jpeg") },
  { id: 36, address: require("../images/others/other4.jpeg") },
];

export default arr;
